### ISSUE TITLE
Facing Strange Artifacts in Generating Results

### ISSUE THREAD

**Issue by MKFMIKU** [EricElmoznino/deep_bilateral_network#2]
Hi, Thanks for your wonderful work.
I'm using the pre-trained model in `saved_runs/best/model.pth` to test my own images,
and some strange artifacts are shown in the squared area as below:

![wrong_results](https://user-images.githubusercontent.com/13622651/57225891-33282e80-7040-11e9-9fb9-4e14bec036fd.png)

Could you please give me any advice on finding the bug?

**Comment by EricElmoznino** [comment]
Hi. There’s no bug. That model was trained on a task I’m interested in, not the tasks in the paper. You’ll have to retrain on the task you’re interested in.
