### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by JiaqianLi** [EricElmoznino/deep_bilateral_network#3]
Hello, thank you for your work! I have prepared the dataset and then run the code. When I train the model Curves or NN use "python train.py Curves" there exists an error like this and I don't know how to solve it so I need your help. Looking forward for your reply~ Thanks.
`Starting epoch: 1
Segmentation fault (core dumped)`

**Comment by EricElmoznino** [comment]
Sorry, tough to solve with just a segfault. Not able to reproduce either when I try running on the `data/debug` dataset. Can you try running on that one?

**Comment by JiaqianLi** [comment]
Thank you for reply. I have checked the code and found the error might be at 
[https://github.com/EricElmoznino/deep_bilateral_network/blob/a30feb43aa3f448be013997665408c69c3818f53/models/layers.py#L40](url)
But I have built the custom layer with C++ implementation as metioned and got the result as this:
`Processing dependencies for bilateral-slice-op==0.0.0
Finished processing dependencies for bilateral-slice-op==0.0.0
`
Howerver, I still have the problem above and do not know how to solve it. QAQ

**Comment by EricElmoznino** [comment]
I just created a new environment on both Mac and Linux, installed the dependencies, installed the bilateral_slice layer, and ran on the `data/debug` dataset and everything worked. I cannot reproduce your issue, I'm sorry.

**Comment by JiaqianLi** [comment]
May I ask what is your environment, my current environment is python 3.7 and pytorch 1.0.1. At the same time,  I want to know whether the result about the dependencies metioned above is right ?  Thank you~

**Comment by EricElmoznino** [comment]
My python is 3.7 and pytorch is 1.1.0. The result you get when building the bilateral_slice op is correct. The issue is likely on the C++ side of things where we may have different compilers, but my knowledge of C++ isn't great. I suggest first trying on another machine.
