### ISSUE TITLE
model parameter setting

### ISSUE THREAD

**Issue by leemengxing** [EricElmoznino/deep_bilateral_network#6]
what is the parameter setting in configuration.py for best/model.pth?

**Comment by liujianzhao6328057** [comment]
have you solved the problem?

**Comment by EricElmoznino** [comment]
Hey. The parameters are probably the default ones specified in the argument parser. It’s been a while so I don’t remember. In any case, I believe that model was trained using a private dataset which you won’t have access to. Parameters will depend on your dataset.
