### ISSUE TITLE
What's difference of NN and curve?

### ISSUE THREAD

**Issue by ewen1024** [EricElmoznino/deep_bilateral_network#8]
I have got the model running and the result seems good now. 
The question is how to choose the training method" NN and curve", what's pros and cons?

By the way, I am now finding ways to port to coreml and ncnn.

Thank you

**Comment by EricElmoznino** [comment]
Difference is in how the guide map is specified.  Don’t recall the theoretical differences (they might mention them in the paper), but in my case “curve” always worked better. It’s a bit more annoying to implement in CoreML, but definitely doable.

Congrats on porting! Most annoying part of the process. If you don’t mind my asking, what’s the use-case and task you’re trying to learn?

**Comment by ewen1024** [comment]
In my case, the videos shoot on our machinces suffer from poor image quality(due to the limitation of lenses and sensors), so we'd use the model to 'brighten' the image to some extent.

By the way, any tests on the number of guide_pts?

**Comment by EricElmoznino** [comment]
No that I have access to, sorry. All tests I did are from around a year ago at a company I no longer work at.
